from typing import Dict, List, Any

Rule = Dict[str, Any]

RULES: List[Rule] = [
    # Phase 0: Method -> Operation
    {"name": "Op_Read_GET", "priority": 1, "if": {"method": "GET"}, "then": {"operation": "read"}},
    {"name": "Op_Create_POST", "priority": 1, "if": {"method": "POST"}, "then": {"operation": "create"}},
    {"name": "Op_Replace_PUT", "priority": 1, "if": {"method": "PUT"}, "then": {"operation": "replace"}},
    {"name": "Op_Update_PATCH", "priority": 1, "if": {"method": "PATCH"}, "then": {"operation": "update"}},
    {"name": "Op_Delete_DELETE", "priority": 1, "if": {"method": "DELETE"}, "then": {"operation": "delete"}},

    # Phase 1: Symptoms -> Cause (Diagnosis)

    # 400
    {
        "name": "Cause_GetWithJsonBody_400",
        "priority": 20,
        "if": {"status_code": 400, "method": "GET", "error_keyword": "json"},
        "then": {
            "category": "validation",
            "cause": "get_with_json_body",
            "diagnosis": "GET request contains an invalid or unexpected JSON body.",
        },
    },
    {
        "name": "Cause_InvalidJson_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "json"},
        "then": {"category": "validation", "cause": "invalid_json", "diagnosis": "Invalid JSON body."},
    },
    {
        "name": "Cause_MissingField_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "missing_field"},
        "then": {
            "category": "validation",
            "cause": "missing_required_field",
            "diagnosis": "Missing required field in request.",
        },
    },
    {
        "name": "Cause_InvalidType_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "type"},
        "then": {"category": "validation", "cause": "invalid_data_type", "diagnosis": "Invalid data type in request payload."},
    },
    {
        "name": "Cause_ValidationFailed_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "validation"},
        "then": {"category": "validation", "cause": "validation_failed", "diagnosis": "Request validation failed."},
    },
    {
        "name": "Cause_EmptyBody_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "empty"},
        "then": {"category": "validation", "cause": "empty_body", "diagnosis": "Empty request body."},
    },
    {
        "name": "Cause_PayloadTooLarge_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "size"},
        "then": {"category": "validation", "cause": "payload_too_large", "diagnosis": "Request payload too large."},
    },
    {
        "name": "Cause_MalformedQuery_400",
        "priority": 15,
        "if": {"status_code": 400, "error_keyword": "query"},
        "then": {"category": "validation", "cause": "malformed_query", "diagnosis": "Malformed query parameters."},
    },
    {
        "name": "Cause_BadRequest_400_Generic",
        "priority": 0,
        "if": {"status_code": 400},
        "then": {"category": "validation", "cause": "bad_request_generic", "diagnosis": "Bad request (client error)."},
    },

    # 401
    {
        "name": "Cause_MissingAuthHeader_401",
        "priority": 20,
        "if": {"status_code": 401, "has_auth_header": "no"},
        "then": {"category": "auth", "cause": "missing_auth_header", "diagnosis": "Missing authentication header."},
    },
    {
        "name": "Cause_InvalidCredentials_401",
        "priority": 10,
        "if": {"status_code": 401, "has_auth_header": "yes"},
        "then": {
            "category": "auth",
            "cause": "invalid_or_expired_credentials",
            "diagnosis": "Invalid or expired authentication credentials.",
        },
    },
    {"name": "Cause_ExpiredToken_401", "priority": 15, "if": {"status_code": 401, "error_keyword": "expired"},
     "then": {"category": "auth", "cause": "expired_token", "diagnosis": "Expired authentication token."}},
    {"name": "Cause_MalformedToken_401", "priority": 15, "if": {"status_code": 401, "error_keyword": "malformed"},
     "then": {"category": "auth", "cause": "malformed_token", "diagnosis": "Malformed authentication token."}},
    {"name": "Cause_TokenSignatureInvalid_401", "priority": 15, "if": {"status_code": 401, "error_keyword": "signature"},
     "then": {"category": "auth", "cause": "invalid_token_signature", "diagnosis": "Invalid token signature."}},
    {"name": "Cause_TokenRevoked_401", "priority": 15, "if": {"status_code": 401, "error_keyword": "revoked"},
     "then": {"category": "auth", "cause": "revoked_token", "diagnosis": "Authentication token has been revoked."}},
    {"name": "Cause_MissingApiKey_401", "priority": 15, "if": {"status_code": 401, "error_keyword": "api_key"},
     "then": {"category": "auth", "cause": "missing_api_key", "diagnosis": "Missing API key."}},
    {"name": "Cause_WrongAuthScheme_401", "priority": 15, "if": {"status_code": 401, "error_keyword": "scheme"},
     "then": {"category": "auth", "cause": "wrong_auth_scheme", "diagnosis": "Incorrect authentication scheme."}},
    {
        "name": "Cause_Unauthorized_401_Generic",
        "priority": 0,
        "if": {"status_code": 401},
        "then": {"category": "auth", "cause": "unauthorized_generic", "diagnosis": "Unauthorized request (authentication problem)."},
    },

    # 403
    {"name": "Cause_InternalEndpointForbidden_403_GET", "priority": 25,
     "if": {"status_code": 403, "client_type": "public_api", "method": "GET"},
     "then": {"category": "authorization", "cause": "internal_endpoint_forbidden", "diagnosis": "Attempt to access internal endpoint (GET)."}},
    {"name": "Cause_InternalEndpointForbidden_403_POST", "priority": 25,
     "if": {"status_code": 403, "client_type": "public_api", "method": "POST"},
     "then": {"category": "authorization", "cause": "internal_endpoint_forbidden", "diagnosis": "Attempt to access internal endpoint (POST)."}},
    {"name": "Cause_InternalEndpointForbidden_403_PUT", "priority": 25,
     "if": {"status_code": 403, "client_type": "public_api", "method": "PUT"},
     "then": {"category": "authorization", "cause": "internal_endpoint_forbidden", "diagnosis": "Attempt to access internal endpoint (PUT)."}},
    {"name": "Cause_InternalEndpointForbidden_403_PATCH", "priority": 25,
     "if": {"status_code": 403, "client_type": "public_api", "method": "PATCH"},
     "then": {"category": "authorization", "cause": "internal_endpoint_forbidden", "diagnosis": "Attempt to access internal endpoint (PATCH)."}},
    {"name": "Cause_InternalEndpointForbidden_403_DELETE", "priority": 25,
     "if": {"status_code": 403, "client_type": "public_api", "method": "DELETE"},
     "then": {"category": "authorization", "cause": "internal_endpoint_forbidden", "diagnosis": "Attempt to access internal endpoint (DELETE)."}},

    {"name": "Cause_MissingRole_403", "priority": 15, "if": {"status_code": 403, "error_keyword": "role"},
     "then": {"category": "authorization", "cause": "missing_role", "diagnosis": "Missing required role or permission."}},
    {"name": "Cause_ScopeNotAllowed_403", "priority": 15, "if": {"status_code": 403, "error_keyword": "scope"},
     "then": {"category": "authorization", "cause": "scope_not_allowed", "diagnosis": "Insufficient authorization scope."}},
    {"name": "Cause_AccessPolicyDenied_403", "priority": 15, "if": {"status_code": 403, "error_keyword": "policy"},
     "then": {"category": "authorization", "cause": "policy_denied", "diagnosis": "Access denied by policy."}},
    {"name": "Cause_IpBlocked_403", "priority": 15, "if": {"status_code": 403, "error_keyword": "ip"},
     "then": {"category": "authorization", "cause": "ip_blocked", "diagnosis": "Client IP address is blocked."}},

    # Method-specific 403
    {"name": "Cause_DeleteForbidden_403", "priority": 12, "if": {"status_code": 403, "method": "DELETE"},
     "then": {"category": "authorization", "cause": "delete_forbidden", "diagnosis": "DELETE operation is forbidden for this resource."}},
    {"name": "Cause_PatchForbidden_403", "priority": 12, "if": {"status_code": 403, "method": "PATCH"},
     "then": {"category": "authorization", "cause": "patch_forbidden", "diagnosis": "PATCH operation is forbidden for this resource."}},
    {"name": "Cause_PutForbidden_403", "priority": 12, "if": {"status_code": 403, "method": "PUT"},
     "then": {"category": "authorization", "cause": "put_forbidden", "diagnosis": "PUT operation is forbidden for this resource."}},
    {"name": "Cause_PostForbidden_403", "priority": 12, "if": {"status_code": 403, "method": "POST"},
     "then": {"category": "authorization", "cause": "post_forbidden", "diagnosis": "POST (create) operation is forbidden for this resource."}},

    {
        "name": "Cause_Forbidden_403_Generic",
        "priority": 0,
        "if": {"status_code": 403},
        "then": {"category": "authorization", "cause": "forbidden_generic", "diagnosis": "Forbidden request (authorization problem)."},
    },

    # 404
    {"name": "Cause_WrongApiVersion_404", "priority": 20, "if": {"status_code": 404, "error_keyword": "version"},
     "then": {"category": "routing", "cause": "wrong_api_version", "diagnosis": "Incorrect API version in request path."}},
    {"name": "Cause_ResourceNotFound_404", "priority": 20, "if": {"status_code": 404, "error_keyword": "resource"},
     "then": {"category": "routing", "cause": "resource_not_found", "diagnosis": "Requested resource does not exist."}},
    {"name": "Cause_TrailingSlashIssue_404", "priority": 20, "if": {"status_code": 404, "error_keyword": "slash"},
     "then": {"category": "routing", "cause": "trailing_slash_issue", "diagnosis": "Incorrect trailing slash in endpoint URL."}},
    {"name": "Cause_DeprecatedEndpoint_404", "priority": 20, "if": {"status_code": 404, "error_keyword": "deprecated"},
     "then": {"category": "routing", "cause": "deprecated_endpoint", "diagnosis": "Deprecated endpoint."}},

    # Method-specific 404
    {"name": "Cause_NotFoundOnCreate_404_POST", "priority": 10, "if": {"status_code": 404, "operation": "create"},
     "then": {"category": "routing", "cause": "write_endpoint_not_found", "diagnosis": "Create endpoint not found (incorrect route for POST)."}},
    {"name": "Cause_404_UpdateTargetNotFound", "priority": 10, "if": {"status_code": 404, "operation": "update"},
     "then": {"category": "routing", "cause": "update_target_not_found", "diagnosis": "PATCH target resource not found (id does not exist)."}},
    {"name": "Cause_404_ReplaceTargetNotFound", "priority": 10, "if": {"status_code": 404, "operation": "replace"},
     "then": {"category": "routing", "cause": "replace_target_not_found", "diagnosis": "PUT target resource not found (id does not exist)."}},
    {"name": "Cause_404_DeleteTargetNotFound", "priority": 10, "if": {"status_code": 404, "operation": "delete"},
     "then": {"category": "routing", "cause": "delete_target_not_found", "diagnosis": "DELETE target resource not found (id does not exist)."}},

    {
        "name": "Cause_NotFound_404_Generic",
        "priority": 0,
        "if": {"status_code": 404},
        "then": {"category": "routing", "cause": "not_found_generic", "diagnosis": "Endpoint not found (wrong path or route)."},
    },

    # 405
    {"name": "Cause_MethodNotAllowed_GET_405", "priority": 20, "if": {"status_code": 405, "method": "GET"},
     "then": {"category": "routing", "cause": "method_not_allowed_get", "diagnosis": "GET is not allowed for this endpoint."}},
    {"name": "Cause_MethodNotAllowed_POST_405", "priority": 20, "if": {"status_code": 405, "method": "POST"},
     "then": {"category": "routing", "cause": "method_not_allowed_post", "diagnosis": "POST is not allowed for this endpoint."}},
    {"name": "Cause_MethodNotAllowed_PUT_405", "priority": 20, "if": {"status_code": 405, "method": "PUT"},
     "then": {"category": "routing", "cause": "method_not_allowed_put", "diagnosis": "PUT is not allowed for this endpoint."}},
    {"name": "Cause_MethodNotAllowed_DELETE_405", "priority": 20, "if": {"status_code": 405, "method": "DELETE"},
     "then": {"category": "routing", "cause": "method_not_allowed_delete", "diagnosis": "DELETE is not allowed for this endpoint."}},
    {"name": "Cause_MethodNotAllowed_PATCH_405", "priority": 20, "if": {"status_code": 405, "method": "PATCH"},
     "then": {"category": "routing", "cause": "method_not_allowed_patch", "diagnosis": "PATCH is not allowed for this endpoint."}},
    {
        "name": "Cause_MethodNotAllowed_405_Generic",
        "priority": 0,
        "if": {"status_code": 405},
        "then": {"category": "routing", "cause": "method_not_allowed", "diagnosis": "Method not allowed for this endpoint."},
    },

    # 415
    {"name": "Cause_415_WriteNeedsContentType_POST", "priority": 10, "if": {"status_code": 415, "method": "POST"},
     "then": {"category": "validation", "cause": "write_missing_or_wrong_content_type",
              "diagnosis": "POST body has unsupported or missing Content-Type."}},
    {"name": "Cause_415_WriteNeedsContentType_PUT", "priority": 10, "if": {"status_code": 415, "method": "PUT"},
     "then": {"category": "validation", "cause": "write_missing_or_wrong_content_type",
              "diagnosis": "PUT body has unsupported or missing Content-Type."}},
    {"name": "Cause_415_WriteNeedsContentType_PATCH", "priority": 10, "if": {"status_code": 415, "method": "PATCH"},
     "then": {"category": "validation", "cause": "write_missing_or_wrong_content_type",
              "diagnosis": "PATCH body has unsupported or missing Content-Type."}},
    {
        "name": "Cause_UnsupportedMediaType_415",
        "priority": 0,
        "if": {"status_code": 415},
        "then": {"category": "validation", "cause": "unsupported_media_type", "diagnosis": "Unsupported media type."},
    },

    # 429
    {"name": "Cause_WriteRateLimited_429_Public_POST", "priority": 15,
     "if": {"status_code": 429, "client_type": "public_api", "method": "POST"},
     "then": {"category": "rate_limit", "cause": "write_rate_limited", "diagnosis": "Rate limit exceeded on write operation (POST)."}},
    {"name": "Cause_WriteRateLimited_429_Public_PUT", "priority": 15,
     "if": {"status_code": 429, "client_type": "public_api", "method": "PUT"},
     "then": {"category": "rate_limit", "cause": "write_rate_limited", "diagnosis": "Rate limit exceeded on write operation (PUT)."}},
    {"name": "Cause_WriteRateLimited_429_Public_PATCH", "priority": 15,
     "if": {"status_code": 429, "client_type": "public_api", "method": "PATCH"},
     "then": {"category": "rate_limit", "cause": "write_rate_limited", "diagnosis": "Rate limit exceeded on write operation (PATCH)."}},
    {"name": "Cause_WriteRateLimited_429_Public_DELETE", "priority": 15,
     "if": {"status_code": 429, "client_type": "public_api", "method": "DELETE"},
     "then": {"category": "rate_limit", "cause": "write_rate_limited", "diagnosis": "Rate limit exceeded on write operation (DELETE)."}},

    {"name": "Cause_PublicApiRateLimit_429", "priority": 10, "if": {"status_code": 429, "client_type": "public_api"},
     "then": {"category": "rate_limit", "cause": "public_api_rate_limit", "diagnosis": "Public API rate limit exceeded."}},
    {
        "name": "Cause_TooManyRequests_429_Generic",
        "priority": 0,
        "if": {"status_code": 429},
        "then": {"category": "rate_limit", "cause": "rate_limited_generic", "diagnosis": "Rate limit exceeded."},
    },

    # 500
    {"name": "Cause_NullPointer_500", "priority": 15, "if": {"status_code": 500, "error_keyword": "null"},
     "then": {"category": "server", "cause": "null_reference", "diagnosis": "Unhandled null reference in backend."}},
    {"name": "Cause_ConfigError_500", "priority": 15, "if": {"status_code": 500, "error_keyword": "config"},
     "then": {"category": "server", "cause": "config_error", "diagnosis": "Backend configuration error."}},
    {"name": "Cause_BackendTimeout_500", "priority": 15, "if": {"status_code": 500, "error_keyword": "timeout"},
     "then": {"category": "server", "cause": "backend_timeout", "diagnosis": "Backend service timeout."}},
    {"name": "Cause_DbConnectionError_500", "priority": 15, "if": {"status_code": 500, "error_keyword": "db_connection"},
     "then": {"category": "server", "cause": "db_connection_error", "diagnosis": "Database connection problem."}},
    {"name": "Cause_OutOfMemory_500", "priority": 15, "if": {"status_code": 500, "error_keyword": "memory"},
     "then": {"category": "server", "cause": "out_of_memory", "diagnosis": "Out-of-memory error in backend."}},
    {
        "name": "Cause_ServerError_500_Generic",
        "priority": 0,
        "if": {"status_code": 500},
        "then": {"category": "server", "cause": "server_error_generic", "diagnosis": "Internal server error (unexpected failure in backend)."},
    },

    # 502 / 503 / 504
    {"name": "Cause_DependencyFailure_502", "priority": 0, "if": {"status_code": 502},
     "then": {"category": "server", "cause": "bad_gateway_dependency", "diagnosis": "Bad gateway from downstream service."}},
    {"name": "Cause_CircuitBreakerOpen_503", "priority": 10, "if": {"status_code": 503, "error_keyword": "circuit"},
     "then": {"category": "server", "cause": "circuit_breaker_open", "diagnosis": "Circuit breaker open."}},
    {"name": "Cause_ServiceUnavailable_503", "priority": 0, "if": {"status_code": 503},
     "then": {"category": "server", "cause": "service_unavailable", "diagnosis": "Service temporarily unavailable."}},
    {"name": "Cause_GatewayTimeout_504_Generic", "priority": 0, "if": {"status_code": 504},
     "then": {"category": "server", "cause": "gateway_timeout", "diagnosis": "Gateway timeout (upstream service did not respond in time)."}},

    # Phase 2: Cause -> Recommendation

    # 400
    {"name": "Reco_GetWithJsonBody_400", "priority": 10, "if": {"cause": "get_with_json_body"},
     "then": {"recommendation": "Avoid sending a JSON body with GET. Move data to query parameters or use POST if a body is required."}},
    {"name": "Reco_InvalidJson", "priority": 0, "if": {"cause": "invalid_json"},
     "then": {"recommendation": "Validate JSON syntax and ensure the payload matches the API schema."}},
    {"name": "Reco_MissingRequiredField", "priority": 0, "if": {"cause": "missing_required_field"},
     "then": {"recommendation": "Check the API documentation for required fields and include them."}},
    {"name": "Reco_InvalidDataType", "priority": 0, "if": {"cause": "invalid_data_type"},
     "then": {"recommendation": "Verify field types match the API schema (e.g. string vs number)."}},
    {"name": "Reco_ValidationFailed", "priority": 0, "if": {"cause": "validation_failed"},
     "then": {"recommendation": "Check validation rules and constraints defined by the API."}},
    {"name": "Reco_EmptyBody", "priority": 0, "if": {"cause": "empty_body"},
     "then": {"recommendation": "Ensure the request body is not empty and contains required data."}},
    {"name": "Reco_PayloadTooLarge", "priority": 0, "if": {"cause": "payload_too_large"},
     "then": {"recommendation": "Reduce payload size or split the request into smaller chunks."}},
    {"name": "Reco_MalformedQuery", "priority": 0, "if": {"cause": "malformed_query"},
     "then": {"recommendation": "Verify query parameter names, values, and encoding."}},
    {"name": "Reco_BadRequest_Generic", "priority": 0, "if": {"cause": "bad_request_generic"},
     "then": {"recommendation": "Check the request body, query parameters, and required fields."}},

    # 401
    {"name": "Reco_MissingAuthHeader", "priority": 0, "if": {"cause": "missing_auth_header"},
     "then": {"recommendation": "Include a valid Authorization header in the request."}},
    {"name": "Reco_InvalidOrExpiredCredentials", "priority": 0, "if": {"cause": "invalid_or_expired_credentials"},
     "then": {"recommendation": "Verify token validity, expiration time, and authentication configuration."}},
    {"name": "Reco_ExpiredToken", "priority": 0, "if": {"cause": "expired_token"},
     "then": {"recommendation": "Refresh the token or log in again to obtain a new one."}},
    {"name": "Reco_MalformedToken", "priority": 0, "if": {"cause": "malformed_token"},
     "then": {"recommendation": "Check token format and ensure it follows the expected structure."}},
    {"name": "Reco_InvalidTokenSignature", "priority": 0, "if": {"cause": "invalid_token_signature"},
     "then": {"recommendation": "Verify token signing key and authentication configuration."}},
    {"name": "Reco_RevokedToken", "priority": 0, "if": {"cause": "revoked_token"},
     "then": {"recommendation": "Generate a new token and ensure it is still active."}},
    {"name": "Reco_MissingApiKey", "priority": 0, "if": {"cause": "missing_api_key"},
     "then": {"recommendation": "Include a valid API key in the request headers."}},
    {"name": "Reco_WrongAuthScheme", "priority": 0, "if": {"cause": "wrong_auth_scheme"},
     "then": {"recommendation": "Ensure the Authorization header uses the correct scheme (e.g. Bearer)."}},
    {"name": "Reco_Unauthorized_Generic", "priority": 0, "if": {"cause": "unauthorized_generic"},
     "then": {"recommendation": "Verify that the request includes valid authentication credentials."}},

    # 403
    {"name": "Reco_InternalEndpointForbidden", "priority": 10, "if": {"cause": "internal_endpoint_forbidden"},
     "then": {"recommendation": "Use the correct public endpoint or call the API from an internal service."}},
    {"name": "Reco_MissingRole", "priority": 0, "if": {"cause": "missing_role"},
     "then": {"recommendation": "Assign the required role or permission to the user or service."}},
    {"name": "Reco_ScopeNotAllowed", "priority": 0, "if": {"cause": "scope_not_allowed"},
     "then": {"recommendation": "Request a token with the necessary scopes."}},
    {"name": "Reco_PolicyDenied", "priority": 0, "if": {"cause": "policy_denied"},
     "then": {"recommendation": "Review access policies and security rules for this endpoint."}},
    {"name": "Reco_IpBlocked", "priority": 0, "if": {"cause": "ip_blocked"},
     "then": {"recommendation": "Check firewall rules or IP allowlists."}},
    {"name": "Reco_DeleteForbidden_403", "priority": 0, "if": {"cause": "delete_forbidden"},
     "then": {"recommendation": "Check whether the user/service has delete permissions and whether the resource is allowed to be deleted."}},
    {"name": "Reco_PatchForbidden_403", "priority": 0, "if": {"cause": "patch_forbidden"},
     "then": {"recommendation": "Check update permissions/scopes and whether partial updates are allowed for this endpoint."}},
    {"name": "Reco_PutForbidden_403", "priority": 0, "if": {"cause": "put_forbidden"},
     "then": {"recommendation": "Check update permissions/scopes and whether full replacement is allowed for this endpoint."}},
    {"name": "Reco_PostForbidden_403", "priority": 0, "if": {"cause": "post_forbidden"},
     "then": {"recommendation": "Check create permissions/scopes or whether this resource is read-only."}},
    {"name": "Reco_Forbidden_Generic", "priority": 0, "if": {"cause": "forbidden_generic"},
     "then": {"recommendation": "Check user or service permissions and access control rules."}},

    # 404
    {"name": "Reco_WrongApiVersion", "priority": 0, "if": {"cause": "wrong_api_version"},
     "then": {"recommendation": "Verify the API version used in the URL."}},
    {"name": "Reco_ResourceNotFound", "priority": 0, "if": {"cause": "resource_not_found"},
     "then": {"recommendation": "Verify resource identifiers and existence."}},
    {"name": "Reco_TrailingSlashIssue", "priority": 0, "if": {"cause": "trailing_slash_issue"},
     "then": {"recommendation": "Check whether the endpoint requires or forbids a trailing slash."}},
    {"name": "Reco_DeprecatedEndpoint", "priority": 0, "if": {"cause": "deprecated_endpoint"},
     "then": {"recommendation": "Update the client to use the latest supported endpoint."}},
    {"name": "Reco_WriteEndpointNotFound_404", "priority": 0, "if": {"cause": "write_endpoint_not_found"},
     "then": {"recommendation": "Verify you are using the correct POST endpoint (path and API version). Some APIs use a different path for create actions."}},
    {"name": "Reco_404_UpdateTargetNotFound", "priority": 0, "if": {"cause": "update_target_not_found"},
     "then": {"recommendation": "Verify the resource ID exists and that the URL matches the API’s item route (e.g. /items/{id})."}},
    {"name": "Reco_404_ReplaceTargetNotFound", "priority": 0, "if": {"cause": "replace_target_not_found"},
     "then": {"recommendation": "Verify the resource ID exists and that the URL matches the API’s item route (e.g. /items/{id})."}},
    {"name": "Reco_404_DeleteTargetNotFound", "priority": 0, "if": {"cause": "delete_target_not_found"},
     "then": {"recommendation": "Verify the resource ID exists and that the URL matches the API’s item route (e.g. /items/{id})."}},
    {"name": "Reco_NotFound_Generic", "priority": 0, "if": {"cause": "not_found_generic"},
     "then": {"recommendation": "Check the request path, API version, and routing configuration."}},

    # 405
    {"name": "Reco_MethodNotAllowed_Generic", "priority": 0, "if": {"cause": "method_not_allowed"},
     "then": {"recommendation": "Check which HTTP methods are supported and adjust the request."}},
    {"name": "Reco_MethodNotAllowed_GET", "priority": 0, "if": {"cause": "method_not_allowed_get"},
     "then": {"recommendation": "Replace GET with the method specified by the API for this endpoint (commonly POST or PUT)."}},
    {"name": "Reco_MethodNotAllowed_POST", "priority": 0, "if": {"cause": "method_not_allowed_post"},
     "then": {"recommendation": "Replace POST with the correct method for this endpoint (commonly GET for retrieval or PUT/PATCH for updates)."}},
    {"name": "Reco_MethodNotAllowed_PUT", "priority": 0, "if": {"cause": "method_not_allowed_put"},
     "then": {"recommendation": "Use the update method supported by this endpoint (often PATCH or POST), based on documentation."}},
    {"name": "Reco_MethodNotAllowed_DELETE", "priority": 0, "if": {"cause": "method_not_allowed_delete"},
     "then": {"recommendation": "Verify whether deletion is supported. If it is, use the correct endpoint and ensure permissions allow DELETE."}},
    {"name": "Reco_MethodNotAllowed_PATCH", "priority": 0, "if": {"cause": "method_not_allowed_patch"},
     "then": {"recommendation": "If partial updates are not supported, use PUT (full update) or the method specified in the API docs."}},

    # 415
    {"name": "Reco_415_WriteNeedsContentType", "priority": 10, "if": {"cause": "write_missing_or_wrong_content_type"},
     "then": {"recommendation": "Set Content-Type correctly (commonly application/json) and ensure the body encoding matches what the API expects."}},
    {"name": "Reco_UnsupportedMediaType", "priority": 0, "if": {"cause": "unsupported_media_type"},
     "then": {"recommendation": "Set the Content-Type header to a format supported by the API."}},

    # 429
    {"name": "Reco_WriteRateLimited_429", "priority": 10, "if": {"cause": "write_rate_limited"},
     "then": {"recommendation": "Implement backoff/retries and consider batching writes or requesting higher write quotas."}},
    {"name": "Reco_PublicApiRateLimit", "priority": 0, "if": {"cause": "public_api_rate_limit"},
     "then": {"recommendation": "Add client-side rate limiting and consider using API keys with higher quotas."}},
    {"name": "Reco_RateLimited_Generic", "priority": 0, "if": {"cause": "rate_limited_generic"},
     "then": {"recommendation": "Reduce request frequency or implement exponential backoff."}},

    # 500+
    {"name": "Reco_ServerError_Generic", "priority": 0, "if": {"cause": "server_error_generic"},
     "then": {"recommendation": "Inspect backend logs and recent code changes for unhandled errors."}},
    {"name": "Reco_NullReference", "priority": 0, "if": {"cause": "null_reference"},
     "then": {"recommendation": "Inspect backend code for missing null checks."}},
    {"name": "Reco_ConfigError", "priority": 0, "if": {"cause": "config_error"},
     "then": {"recommendation": "Verify environment variables and configuration files."}},
    {"name": "Reco_BackendTimeout", "priority": 0, "if": {"cause": "backend_timeout"},
     "then": {"recommendation": "Check downstream service latency and increase timeout limits if needed."}},
    {"name": "Reco_DbConnectionError", "priority": 0, "if": {"cause": "db_connection_error"},
     "then": {"recommendation": "Verify database availability, connection strings, and network access."}},
    {"name": "Reco_OutOfMemory", "priority": 0, "if": {"cause": "out_of_memory"},
     "then": {"recommendation": "Check memory usage and adjust resource limits."}},
    {"name": "Reco_BadGatewayDependency", "priority": 0, "if": {"cause": "bad_gateway_dependency"},
     "then": {"recommendation": "Check availability and health of dependent services."}},
    {"name": "Reco_ServiceUnavailable", "priority": 0, "if": {"cause": "service_unavailable"},
     "then": {"recommendation": "Retry later or check service health and scaling."}},
    {"name": "Reco_CircuitBreakerOpen", "priority": 0, "if": {"cause": "circuit_breaker_open"},
     "then": {"recommendation": "Allow time for recovery or investigate downstream failures."}},
    {"name": "Reco_GatewayTimeout", "priority": 0, "if": {"cause": "gateway_timeout"},
     "then": {"recommendation": "Check downstream service availability and timeout settings."}},
]
